[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-traits"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.2.0"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.1"
gimli = { version = "0.16.0", optional = true }
parity-wasm = "0.31.0"
twiggy-ir = { version = "=0.2.0", path = "../ir" }
csv = "1.0.0-beta.5"
regex = "1.0.0"

[features]
default = ["dwarf"]
dwarf = ["gimli"]
emit_json = []
emit_csv = []
emit_text = []
